Don't exit script when repository not found

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -49,7 +49,8 @@ jobs:
           inlineScript: |
             set -e
             cd benefit
-            response=$(az acr repository show-tags -n $(acrName) --repository $(repositoryBenefit) | grep ($imageTagBenefit))
+            # || true because we don't want script to exit here when return code from az acr is "1"
+            response=$(az acr repository show-tags -n $(acrName) --repository $(repositoryBenefit) | grep ($imageTagBenefit)) || true
             if [ -z "$response" ]; then
               echo "Building $(repositoryBenefit):$(imageTagBenefit) ..."
               az acr build -r $(acrName) -t $(repositoryBenefit):$(imageTagBenefit) -g $(acrResourceGroup) -f ../docker/importer.Dockerfile .
@@ -58,7 +59,7 @@ jobs:
               echo "$(repositoryBenefit):$(imageTagBenefit) already exists"
             fi
             cd ../bulk-scan
-            response=$(az acr repository show-tags -n $(acrName) --repository $(repositoryBulkscan) | grep $(imageTagBulkscan))
+            response=$(az acr repository show-tags -n $(acrName) --repository $(repositoryBulkscan) | grep $(imageTagBulkscan)) || true
             if [ -z "$response" ]; then
               echo "Building $(repositoryBulkscan):$(imageTagBulkscan) ..."
               az acr build -r $(acrName) -t $(repositoryBulkscan):$(imageTagBulkscan) -g $(acrResourceGroup) -f ../docker/importer.Dockerfile .
